### ISSUE TITLE
code update?

### ISSUE THREAD

**Issue by 943fansi** [Lab-ANT/TSAGen#1]
Has the code changed compared to [AprilCal/TSAGen](https://github.com/AprilCal/TSAGen)？

**Comment by AprilCal** [comment]
This version is slightly changed  to support Pearson distribution. All future changes will be updated to this repository. If you encounter any problems, please contact chengyu@nudt.edu.cn

**Comment by 943fansi** [comment]
> This version is slightly changed to support Pearson distribution. All future changes will be updated to this repository. If you encounter any problems, please contact [chengyu@nudt.edu.cn](mailto:chengyu@nudt.edu.cn)
What are the versions of Matlab and python you are using, and do you have details about the corresponding restrictions of the versions?

**Comment by AprilCal** [comment]
> 

This version is compatible with Matlab R2021b and python >= 3.7. As for the restrictions, some institutions are not allowed to access Matlab.

**Comment by 943fansi** [comment]
Thanks @AprilCal
